# Generated by Django 5.2.15 on 2026-06-21 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField()),
                ('duration', models.CharField(help_text="e.g. '2–4 months'", max_length=60)),
                ('icon', models.CharField(blank=True, help_text='Emoji icon, e.g. 📖', max_length=10)),
                ('order', models.PositiveIntegerField(default=0, help_text='Controls display order')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_name', models.CharField(help_text="e.g. 'Morning'", max_length=60)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('availability', models.CharField(choices=[('available', 'Available'), ('limited', 'Limited'), ('full', 'Full')], default='available', max_length=10)),
            ],
            options={
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=150)),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('preferred_timing', models.CharField(max_length=60)),
                ('contact_info', models.CharField(help_text='WhatsApp number or email provided by the user', max_length=150)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('contacted', 'Contacted'), ('enrolled', 'Enrolled'), ('rejected', 'Rejected')], default='pending', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollment_requests', to='academy.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Fee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classes_per_week', models.PositiveIntegerField(default=5)),
                ('class_duration_minutes', models.PositiveIntegerField(default=30)),
                ('monthly_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='PKR', max_length=10)),
                ('course', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fee', to='academy.course')),
            ],
        ),
    ]
